export interface Language {
  code: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface SummaryResponse {
  video: {
    id: string;
    title: string;
    languageCode: string;
    languageName: string;
    isAutoGenerated: boolean;
    durationSeconds: number;
  };
  summary: {
    markdown: string;
    provider: "openai" | "mock";
    model: string;
  };
  stats: {
    transcriptCharacters: number;
    chunks: number;
    elapsedMs: number;
  };
}

interface ApiErrorBody {
  error?: { message?: string; requestId?: string };
}

const API_BASE = (import.meta.env.VITE_API_BASE_URL as string | undefined)?.replace(/\/$/, "") ?? "";

async function parseResponse<T>(response: Response): Promise<T> {
  const body = await response.json().catch(() => ({})) as T & ApiErrorBody;
  if (!response.ok) {
    const requestId = body.error?.requestId ? ` Reference: ${body.error.requestId}` : "";
    throw new Error(`${body.error?.message ?? "The request failed."}${requestId}`);
  }
  return body;
}

export async function fetchLanguages(url: string, signal?: AbortSignal): Promise<Language[]> {
  const response = await fetch(
    `${API_BASE}/api/transcripts/languages?url=${encodeURIComponent(url)}`,
    signal ? { signal } : undefined,
  );
  const body = await parseResponse<{ languages: Language[] }>(response);
  return body.languages;
}

export async function summarizeVideo(url: string, language?: string): Promise<SummaryResponse> {
  const response = await fetch(`${API_BASE}/api/summarize`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ url, ...(language ? { language } : {}) }),
  });
  return parseResponse<SummaryResponse>(response);
}
