import crypto from "node:crypto";
import path from "node:path";
import cors from "cors";
import express, { type ErrorRequestHandler } from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import { z } from "zod";
import { config } from "./config.js";
import { AppError } from "./errors.js";
import { logger } from "./logger.js";
import { createSummarizer } from "./summarizers/index.js";
import { chunkTranscript } from "./text.js";
import { getTranscript, listTranscriptLanguages } from "./transcript-service.js";
import { extractVideoId } from "./youtube-url.js";

const summarizeSchema = z.object({
  url: z.string().trim().min(1).max(2_048),
  language: z.string().trim().min(2).max(35).regex(/^[A-Za-z0-9-]+$/).optional(),
});

export function createApp() {
  const app = express();
  const summarizer = createSummarizer();
  app.disable("x-powered-by");
  app.set("trust proxy", 1);
  app.use(helmet({ crossOriginResourcePolicy: { policy: "cross-origin" } }));
  app.use(cors({
    origin(origin, callback) {
      const allowed = config.CLIENT_ORIGIN.split(",").map((value) => value.trim());
      callback(null, !origin || allowed.includes(origin));
    },
    methods: ["GET", "POST"],
  }));
  app.use((request, response, next) => {
    const requestId = request.header("x-request-id")?.slice(0, 100) || crypto.randomUUID();
    response.setHeader("x-request-id", requestId);
    response.locals.requestId = requestId;
    next();
  });
  app.use(express.json({ limit: "8kb", strict: true }));

  app.get("/api/health", (_request, response) => {
    response.json({
      status: "ok",
      summarizerMode: config.SUMMARIZER_MODE,
      ollamaModel: config.OLLAMA_MODEL,
    });
  });

  app.use("/api", rateLimit({
    windowMs: config.RATE_LIMIT_WINDOW_MS,
    limit: config.RATE_LIMIT_MAX,
    standardHeaders: "draft-8",
    legacyHeaders: false,
    message: { error: { code: "RATE_LIMITED", message: "Too many requests. Please try again shortly." } },
  }));

  app.get("/api/transcripts/languages", async (request, response, next) => {
    try {
      const parsed = z.object({ url: z.string().trim().min(1).max(2_048) }).parse(request.query);
      const videoId = extractVideoId(parsed.url);
      const tracks = await listTranscriptLanguages(videoId);
      response.json({
        videoId,
        languages: tracks.map((track) => ({
          code: track.languageCode,
          name: track.name,
          isAutoGenerated: track.isAutoGenerated,
        })),
      });
    } catch (error) {
      next(error);
    }
  });

  app.post("/api/summarize", async (request, response, next) => {
    const startedAt = Date.now();
    try {
      const body = summarizeSchema.parse(request.body);
      const videoId = extractVideoId(body.url);
      const transcript = await getTranscript(videoId, body.language);
      const chunks = chunkTranscript(transcript.segments);
      const summary = await summarizer.summarize(transcript, chunks);
      logger.info("Video summarized", {
        requestId: response.locals.requestId,
        videoId,
        language: transcript.languageCode,
        chunks: chunks.length,
        provider: summary.provider,
        elapsedMs: Date.now() - startedAt,
      });
      response.json({
        video: {
          id: videoId,
          title: transcript.title,
          languageCode: transcript.languageCode,
          languageName: transcript.languageName,
          isAutoGenerated: transcript.isAutoGenerated,
          durationSeconds: Math.ceil(
            (transcript.segments.at(-1)!.startMs + transcript.segments.at(-1)!.durationMs) / 1_000,
          ),
        },
        summary,
        stats: {
          transcriptCharacters: transcript.text.length,
          chunks: chunks.length,
          elapsedMs: Date.now() - startedAt,
        },
      });
    } catch (error) {
      next(error);
    }
  });

  const clientDist = path.resolve(import.meta.dirname, "../../client/dist");
  app.use(express.static(clientDist, { index: false, maxAge: "1h" }));
  app.get("/{*path}", (request, response, next) => {
    if (request.path.startsWith("/api/")) return next();
    response.sendFile(path.join(clientDist, "index.html"), (error) => error && next(error));
  });

  const errorHandler: ErrorRequestHandler = (error, _request, response, _next) => {
    const requestId = String(response.locals.requestId ?? "");
    if (error instanceof z.ZodError) {
      response.status(400).json({
        error: { code: "INVALID_URL", message: error.issues[0]?.message ?? "Invalid request.", requestId },
      });
      return;
    }
    if (error instanceof SyntaxError && "body" in error) {
      response.status(400).json({
        error: { code: "INVALID_REQUEST", message: "Request body must be valid JSON.", requestId },
      });
      return;
    }
    if (error instanceof AppError) {
      if (error.retryAfterSeconds) response.setHeader("retry-after", error.retryAfterSeconds);
      response.status(error.status).json({ error: { code: error.code, message: error.message, requestId } });
      return;
    }
    logger.error("Unhandled request error", {
      requestId,
      error: error instanceof Error ? error.stack ?? error.message : String(error),
    });
    response.status(500).json({
      error: { code: "INTERNAL_ERROR", message: "An unexpected error occurred.", requestId },
    });
  };
  app.use(errorHandler);
  return app;
}
