import { AppError } from "./errors.js";
import { getCachedTranscript, setCachedTranscript } from "./cache.js";
import { cleanSegments } from "./text.js";
import type { CaptionTrack, Transcript, TranscriptSegment } from "./types.js";
import {
  fetchTranscript,
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptNotAvailableLanguageError,
  YoutubeTranscriptTooManyRequestError,
  YoutubeTranscriptVideoUnavailableError,
} from "youtube-transcript";

const FETCH_TIMEOUT_MS = 12_000;
const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/136.0.0.0 Safari/537.36";

interface PlayerResponse {
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: { title?: string };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl?: string;
        languageCode?: string;
        name?: { simpleText?: string; runs?: Array<{ text?: string }> };
        kind?: string;
        isTranslatable?: boolean;
      }>;
    };
  };
}

async function fetchWithTimeout(url: string): Promise<Response> {
  try {
    return await fetch(url, {
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      headers: {
        "accept-language": "en-US,en;q=0.9",
        "user-agent": USER_AGENT,
      },
      redirect: "follow",
    });
  } catch (error) {
    throw new AppError(
      502,
      "UPSTREAM_ERROR",
      error instanceof Error && error.name === "TimeoutError"
        ? "YouTube took too long to respond. Please try again."
        : "Could not reach YouTube. Please try again.",
    );
  }
}

function extractBalancedJson(source: string, start: number): string | null {
  const objectStart = source.indexOf("{", start);
  if (objectStart < 0) return null;
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = objectStart; index < source.length; index += 1) {
    const character = source[index]!;
    if (inString) {
      if (escaped) escaped = false;
      else if (character === "\\") escaped = true;
      else if (character === "\"") inString = false;
      continue;
    }
    if (character === "\"") inString = true;
    else if (character === "{") depth += 1;
    else if (character === "}" && --depth === 0) return source.slice(objectStart, index + 1);
  }
  return null;
}

function parsePlayerResponse(html: string): PlayerResponse {
  const markers = [
    "var ytInitialPlayerResponse =",
    "ytInitialPlayerResponse =",
    "window[\"ytInitialPlayerResponse\"] =",
  ];
  for (const marker of markers) {
    const markerIndex = html.indexOf(marker);
    if (markerIndex < 0) continue;
    const json = extractBalancedJson(html, markerIndex + marker.length);
    if (!json) continue;
    try {
      return JSON.parse(json) as PlayerResponse;
    } catch {
      // Try the next page representation.
    }
  }
  throw new AppError(502, "UPSTREAM_ERROR", "YouTube returned an unexpected page format.");
}

function trackName(track: NonNullable<
  NonNullable<NonNullable<PlayerResponse["captions"]>["playerCaptionsTracklistRenderer"]>["captionTracks"]
>[number]): string {
  return track.name?.simpleText ?? track.name?.runs?.map((run) => run.text ?? "").join("") ?? track.languageCode ?? "Unknown";
}

function mapTracks(player: PlayerResponse): CaptionTrack[] {
  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return tracks.flatMap((track) =>
    track.baseUrl && track.languageCode
      ? [{
          baseUrl: track.baseUrl,
          languageCode: track.languageCode,
          name: trackName(track),
          isAutoGenerated: track.kind === "asr",
          isTranslatable: track.isTranslatable ?? false,
        }]
      : [],
  );
}

function selectTrack(tracks: CaptionTrack[], requestedLanguage?: string): CaptionTrack {
  if (tracks.length === 0) {
    throw new AppError(
      422,
      "TRANSCRIPT_UNAVAILABLE",
      "This video has no accessible captions or transcript, so it cannot be summarized.",
    );
  }

  const rankManualFirst = (items: CaptionTrack[]) =>
    [...items].sort((a, b) => Number(a.isAutoGenerated) - Number(b.isAutoGenerated));

  if (requestedLanguage) {
    const exact = tracks.filter((track) => track.languageCode.toLowerCase() === requestedLanguage.toLowerCase());
    const base = requestedLanguage.split("-")[0]!.toLowerCase();
    const related = tracks.filter((track) => track.languageCode.split("-")[0]!.toLowerCase() === base);
    const selected = rankManualFirst(exact.length > 0 ? exact : related)[0];
    if (!selected) {
      throw new AppError(422, "LANGUAGE_UNAVAILABLE", `Captions are not available in "${requestedLanguage}".`);
    }
    return selected;
  }

  const english = tracks.filter((track) => track.languageCode.split("-")[0] === "en");
  return rankManualFirst(english.length > 0 ? english : tracks)[0]!;
}

async function loadPlayer(videoId: string): Promise<{ player: PlayerResponse; tracks: CaptionTrack[] }> {
  const response = await fetchWithTimeout(`https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}&hl=en`);
  if (!response.ok) {
    throw new AppError(502, "UPSTREAM_ERROR", "YouTube did not return the video page.");
  }
  const player = parsePlayerResponse(await response.text());
  const status = player.playabilityStatus?.status;
  if (status && status !== "OK") {
    throw new AppError(
      404,
      "VIDEO_UNAVAILABLE",
      player.playabilityStatus?.reason ?? "The video is private, deleted, restricted, or unavailable.",
    );
  }
  return { player, tracks: mapTracks(player) };
}

async function fetchSegments(videoId: string, track: CaptionTrack): Promise<TranscriptSegment[]> {
  try {
    const rows = await fetchTranscript(videoId, {
      lang: track.languageCode,
      fetch: (input, init) => fetch(input, {
        ...init,
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
      }),
    });
    return cleanSegments(rows.map((row) => ({
      text: row.text,
      startMs: row.offset,
      durationMs: row.duration,
    })));
  } catch (error) {
    if (error instanceof YoutubeTranscriptTooManyRequestError) {
      throw new AppError(429, "RATE_LIMITED", "YouTube is temporarily rate-limiting caption requests.", 30);
    }
    if (error instanceof YoutubeTranscriptNotAvailableLanguageError) {
      throw new AppError(422, "LANGUAGE_UNAVAILABLE", `Captions are not available in "${track.languageCode}".`);
    }
    if (
      error instanceof YoutubeTranscriptDisabledError
      || error instanceof YoutubeTranscriptNotAvailableError
    ) {
      throw new AppError(
        422,
        "TRANSCRIPT_UNAVAILABLE",
        "This video has no accessible captions or transcript, so it cannot be summarized.",
      );
    }
    if (error instanceof YoutubeTranscriptVideoUnavailableError) {
      throw new AppError(404, "VIDEO_UNAVAILABLE", "The video is private, deleted, restricted, or unavailable.");
    }
    throw new AppError(
      502,
      "UPSTREAM_ERROR",
      error instanceof Error ? `Could not retrieve captions: ${error.message}` : "Could not retrieve captions.",
    );
  }
}

export async function listTranscriptLanguages(videoId: string): Promise<CaptionTrack[]> {
  const { tracks } = await loadPlayer(videoId);
  if (tracks.length === 0) {
    throw new AppError(
      422,
      "TRANSCRIPT_UNAVAILABLE",
      "This video has no accessible captions or transcript, so it cannot be summarized.",
    );
  }
  return tracks.map(({ baseUrl: _baseUrl, ...track }) => ({ ...track, baseUrl: "" }));
}

export async function getTranscript(videoId: string, requestedLanguage?: string): Promise<Transcript> {
  const cached = await getCachedTranscript(videoId, requestedLanguage);
  if (cached) return cached;

  const { player, tracks } = await loadPlayer(videoId);
  const track = selectTrack(tracks, requestedLanguage);
  const segments = await fetchSegments(videoId, track);
  if (segments.length === 0) {
    throw new AppError(422, "TRANSCRIPT_UNAVAILABLE", "The selected caption track is empty.");
  }

  const transcript: Transcript = {
    videoId,
    title: player.videoDetails?.title ?? "YouTube video",
    languageCode: track.languageCode,
    languageName: track.name,
    isAutoGenerated: track.isAutoGenerated,
    segments,
    text: segments.map((segment) => segment.text).join(" "),
  };
  await setCachedTranscript(transcript, requestedLanguage);
  return transcript;
}
