export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
}

export interface TranscriptSegment {
  text: string;
  startMs: number;
  durationMs: number;
}

export interface Transcript {
  videoId: string;
  title: string;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
  text: string;
}

export interface TranscriptChunk {
  index: number;
  text: string;
  startMs: number;
  endMs: number;
}

export interface VideoSummary {
  markdown: string;
  provider: "openai" | "mock";
  model: string;
}
