import { describe, expect, it, vi } from "vitest";
import type { Transcript, TranscriptChunk } from "../types.js";
import { OllamaSummarizer } from "./ollama.js";

const transcript: Transcript = {
  videoId: "dQw4w9WgXcQ",
  title: "Example video",
  languageCode: "en",
  languageName: "English",
  isAutoGenerated: true,
  text: "The share code is 89169683.",
  segments: [
    { text: "The share code is", startMs: 0, durationMs: 1_000 },
    { text: "89169683.", startMs: 1_000, durationMs: 1_000 },
  ],
};

const chunks: TranscriptChunk[] = [{
  index: 0,
  text: "[0:00] This transcript explains three settings and requires ten skill points for rewards.",
  startMs: 0,
  endMs: 2_000,
}];

describe("OllamaSummarizer", () => {
  it("detects whether the configured model is installed", async () => {
    const fetchImplementation = vi.fn(async () => new Response(JSON.stringify({
      models: [{ name: "phi3:mini" }],
    }))) as unknown as typeof fetch;
    const summarizer = new OllamaSummarizer("http://127.0.0.1:11434", "phi3:mini", 5_000, fetchImplementation);
    await expect(summarizer.isAvailable()).resolves.toBe(true);
  });

  it("returns a normalized local AI summary", async () => {
    const responseText = JSON.stringify({
      overview_ids: [1],
      point_ids: [1],
      detail_ids: [1],
      takeaway_ids: [1],
    });
    const fetchImplementation = vi.fn(async () => new Response(JSON.stringify({
      response: responseText,
    }))) as unknown as typeof fetch;
    const summarizer = new OllamaSummarizer("http://127.0.0.1:11434", "phi3:mini", 5_000, fetchImplementation);
    const result = await summarizer.summarize(transcript, chunks);
    expect(result.provider).toBe("ollama");
    expect(result.model).toBe("phi3:mini");
    expect(result.markdown).toContain("## Short overview\nThe video explains the custom skill-point farming method and required setup.");
    expect(result.markdown).toContain("### 1. Fast skill-point farm (0:00-0:02)");
    expect(result.markdown).toContain("This transcript explains three settings and requires ten skill points for rewards.");
  });

  it("uses selected source text for topics without a specialized section label", async () => {
    const genericTranscript: Transcript = {
      ...transcript,
      title: "A history discussion",
      text: "The archive opened in spring and changed how researchers understood the event.",
    };
    const genericChunks: TranscriptChunk[] = [{
      index: 0,
      text: "[0:00] The archive opened in spring and changed how researchers understood the event.",
      startMs: 0,
      endMs: 3_000,
    }];
    const fetchImplementation = vi.fn(async () => new Response(JSON.stringify({
      response: JSON.stringify({
        overview_ids: [1],
        point_ids: [1],
        detail_ids: [1],
        takeaway_ids: [1],
      }),
    }))) as unknown as typeof fetch;
    const summarizer = new OllamaSummarizer("http://127.0.0.1:11434", "phi3:mini", 5_000, fetchImplementation);
    const result = await summarizer.summarize(genericTranscript, genericChunks);
    expect(result.markdown).toContain(
      "## Short overview\nThe archive opened in spring and changed how researchers understood the event.",
    );
    expect(result.markdown).toContain("### 1. Section 1 (0:00-0:03)");
  });
});
